version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always